version: "3.8"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  api:
    build: .
    ports:
    - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres@db:5432/postgres
    depends_on:
      - db
