name: release-staging

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main
      - heroku-fix

jobs:
  backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Log into GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: TritonSE
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate image tags
        id: docker_meta_gh
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/tritonse/wa-family-literacy-application
      - name: Build and push to GitHub container registry
        uses: docker/build-push-action@v2
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta_gh.outputs.tags }}
          labels: ${{ steps.docker_meta_gh.outputs.labels }}
      - name: Log into Heroku container registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Build and push to Heroku container registry
        uses: docker/build-push-action@v2
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: registry.heroku.com/words-alive-staging/web
      - name: Release to Heroku
        run: heroku container:release web -a words-alive-staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  web:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Build admin site
        working-directory: web
        run: npm run build:prod
        env:
          REACT_APP_BASE_URL: https://api-staging.wordsalive.org
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: web
          environment: staging
